#!/usr/bin/env bash
. globals

cd ~/workspace/223_SAS/
cd $(ls -td -- */ | head -n 1)
cd $(ls -td -- */ | head -n 1)
cd $(ls -td -- */ | head -n 1)

echo $(pwd)
echo $(ls)

masc_flashkernel

beep


0xb566ab8f01819ad732c90588d5216adc90849c61
0xb566ab8f01819ad732c90588d5216adc90849c61
