#!/bin/bash 

. script.conf

splitIp $ROV_IP

if [ ! -d $ROV_HOME ]; then
  mkdir -p $ROV_HOME ;
  echo "created rovsing folder in home"
fi

until sshfs thm@$IP_SPLIT_UPPER.$IP_SPLIT_LOWER:/ $ROV_HOME 
do
  read -p "Failed. Type last ip? " $IP_SPLIT_LOWER
  echo $IP_SPLIT_LOWER
done

echo "Rovsing successfully mounted at $ROV_HOME"


