#!/bin/bash 

. autoGitRepoPahts.sh

THIS_REPO=$(dirs)


NEW_PATHS=$COMMIT_ALL_PATH':'$THIS_REPO

echo $CUR_PATHS
# echo $CUR_PATHS > autoGitRepoPahts.sh

# sed -i.bak 's/^\(COMMIT_ALL_PATH=\).*/\THIS_REPO/' autoGitRepoPahts.sh