#!/usr/bin/env zsh



# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

# source ~/.fonts/*.sh

# echo "ADD: powerlevel9k/powerlevel9k TO ZSH_THEME IN .zshrc"
# echo "ADD: POWERLEVEL9K_MODE='awesome-fontconfig' BEFORE ZSH_THEME IN .zshrc"

# POWERLEVEL9K_MODE='awesome-patched'


ZSH_THEME="robbyrussell"

# POWERLEVEL9K_MODE='awesome-patched'

# Ubuntu Mono 13

# POWERLEVEL9K_PROMPT_ON_NEWLINE=true

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  svn
  autojump
  zsh-autosuggestions
  sublime
)

prompt_svn() {
    local rev branch
    if in_svn; then
        rev=$(svn_get_rev_nr)
        branch=$(svn_get_branch_name)
        if [ `svn_dirty_choose_pwd 1 0` -eq 1 ]; then
            prompt_segment yellow black
            echo -n "$rev@$branch"
            echo -n "±"
        else
            prompt_segment green black
            echo -n "$rev@$branch"
        fi
    fi
}


alias goto_newest_folder='cd $(ls -td -- */ | head -n 1)'
alias in='sudo apt install'
# alias do='./'
alias cleos='docker exec eosio /opt/eosio/bin/cleos --wallet-url http://localhost:8888'

# alias ipp='192.168'

zstyle ':completion:*:(ssh|scp|sftp|rsh|rsync|sshfs):*' hosts "$(echo $USER)@192.168.0." "$(echo $USER)@10.0.100." 
#,thm@10.0.100.
# zstyle ':completion:*:ssh:*' hosts 192.168.0.
# zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync|sshfs):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'
# zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync|sshfs):hosts' hosts 192.168.0.
# zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync|sshfs):hosts' hosts 10.0.100.